version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: ruta_paltas_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ruta_paltas
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: ruta_paltas_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  mysql_data: